# Default values for citizen.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: outsideris/citizen
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Your storage type. Choose either s3 or file
storageType: "s3"

aws:
  # The bucket name that you want to use, only required if the storage type is s3
  bucket: ""
  # The kubernetes secret names and keys to your credentials, only required if the storage type is s3
  # For example,
  # accessKeyID: {"name": "aws-credentials", "key": "AWS_ACCESS_KEY_ID"}
  # secretAccessKey: {"name": "aws-credentials", "key": "AWS_SECRET_ACCESS_KEY"}
  # if your secret is of the form
  #####
  # apiVersion: v1
  # kind: Secret
  # metadata:
  #   name: mysecret
  # type: Opaque
  # data:
  #   username: AKIA...
  #   password: *******
  accessKeyID: {}
  secretAccessKey: {}
